# SPDX-FileCopyrightText: 2025 Enedis Smarties team <dt-dsi-nexus-lab-smarties@enedis.fr>
# SPDX-FileContributor: Jehan BOUSCH
#
# SPDX-License-Identifier: Apache-2.0

# Overload protection configuration
OverloadProtection:
  Enable : true
  RunningPeriodInSeconds : 1
  CurrentLimit :
    ValueInAmps : 16.0 # Used only if Enable is false
    LockDelayInSeconds : 10.0 # Used only if Enable is true
# Vehicle configuration
Vehicle:
  UpdateDataPeriodInSeconds : 5 # Unused if 0
  DataPersistent: false
# Wallbox configuration
Wallbox:
  UpdateDataPeriodInSeconds : 5 # Unused if 0
  DataPersistent: false
# Log configuration
Log:
  Level : "trace" #  Available levels : panic,fatal,error,warn,info,debug,trace
  FilePath : "var/log/tic4eebus.log"
  Rotation:
    PeriodInHours : 24 # each day a new file is created
    PeriodCount : 15 # 15 files maximum are created (15 days of logs)
    PeriodPattern: "-%Y-%m-%d" # each log file name contains the year-month-day of creation

# Data model configuration
DataModel:
  # Csv file configuration (optional)
  Csv:
    FilePath : "var/data/EnergyGuardDataModel.csv"
    Rotation:
      PeriodInHours : 24  # each day a new file is created
      PeriodCount : 7 # 7 files maximum are created (7 days of data model)
      PeriodPattern: "-%Y-%m-%d" # each csv file name contains the year-month-day of creation
  # InfluDB configuration (optional)
  InfluxDb:
    Bucket : "demo-bucket"
    Org : "demo-org"
    Token : "Gj_nwgoqXu4XggIzaiUWFHALKnS5JskdTLzGlSYeJMNkjCD-pyR6Yc5Hvl8NWj5Qo5C80mLvuJAS1IuqOcq4GQ=="
    IpAddress : "http://127.0.0.1"
    TcpPort : 8086
# Tele indformation client (TIC) configuration
TeleInformationClient:
  TIC2Websocket:
    IPAddress : "127.0.0.1"
    TCPPort : 19584
  TICIdentifier:
    SerialNumber : "" # Meter serial number should only be specified if TIC2Websocket handles multiple modems
# EEBUS configuration
EEBUS:
  ServerPort : 4817
  RemoteSKI : "${TIC4EEBUS_REMOTE_SKI}" # example: "50abfe7714d034b8b15e488b91831047657b9ff2"
  CertificateFilePath : "examples/energy-guard.cert"
  PrivateKeyFilePath : "examples/energy-guard.key"
  VendorCode : "i:54076"
  DeviceBrand : "Enedis"
  DeviceModel : "PAC"
  SerialNumber : "12345678"
  HeartbeatTimeoutInSeconds : 2
