# SPDX-FileCopyrightText: 2025 Enedis Smarties team <dt-dsi-nexus-lab-smarties@enedis.fr>
# SPDX-FileContributor: Jehan BOUSCH
#
# SPDX-License-Identifier: Apache-2.0

version = 1

# A simple glob of all files in resources/img/
[[annotations]]
path = ["**/*.sum",
    "**/*.cert",
    "**/*.key",
    "**/*.png",
    "**/*.ico",
    "**/*.pdf",
]
SPDX-FileCopyrightText = "2025 Enedis Smarties team <dt-dsi-nexus-lab-smarties@enedis.fr>"
SPDX-License-Identifier = "Apache-2.0"