# SPDX-FileCopyrightText: 2025 Enedis Smarties team <dt-dsi-nexus-lab-smarties@enedis.fr>
# SPDX-FileContributor: Jehan BOUSCH
#
# SPDX-License-Identifier: Apache-2.0

site_name: tic4eebus
site_url: https://enedis-oss.github.io/tic4eebus/
site_description: Documentation tic4eebus

repo_name: Enedis-OSS/tic4eebus
repo_url: https://github.com/Enedis-OSS/tic4eebus
# Multilingual configuration
plugins:
  - plantuml:
        #puml_url: https://www.plantuml.com/plantuml/
        puml_url: http://plantuml:8080
        puml_keyword: plantuml
        output_format: svg
        theme:
          enabled: true
          light: default/light
          dark: default/dark
  - search
  - i18n:
      docs_structure: folder
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: fr
          default: true
          name: Français
          build: true
          nav_translations:
            Overview: Vue d'ensemble
            Installation: Installation
            Configuration: Configuration
            Architecture: Architecture logicielle
            Model : Modèle de données
        - locale: en
          name: English
          build: true
          nav_translations:
            Overview: Overview
            Installation: Installation
            Configuration: Configuration
            Architecture: Software Architecture
            Model : Data Model

# Site navigation
nav:
  - Overview: index.md
  - Installation: installation.md
  - Configuration: configuration.md
  - Architecture: architecture.md
  - Model: data_model.md

theme:
    name: material
    language: fr
    logo: var/images/logo.png
    favicon: var/images/favicon.ico
    font:
      text: Ubuntu
    features:
          - navigation.sections
          - navigation.expand
          - navigation.indexes
          - toc.integrate
