# SPDX-FileCopyrightText: 2025 Enedis Smarties team <dt-dsi-nexus-lab-smarties@enedis.fr>
# SPDX-FileContributor: Jehan BOUSCH
#
# SPDX-License-Identifier: Apache-2.0

name: Go format Check

on:
  push:
    branches:
      - main
      - dev
  pull_request:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Golang Formatter Check
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
        shell: bash